name: InOutModule_env
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=2.3.1
  - openpyxl=3.1.5
  - pandas=2.3.1
  - pandas-stubs=2.3.0.250703
  - pip=25.1
  - pyomo=6.9.3
  - pytest=8.4.1
  - python=3.12.2
  - python-calamine=0.5.3
  - rich=13.9.4
  - rich-argparse=1.7.1
  - tsam=2.3.9
  - pip:
      - pulp==2.9.0
