name: InOutModule_env
channels:
  - defaults
  - conda-forge
dependencies:
  - openpyxl=3.1.5
  - pandas=2.2.3
  - pandas-stubs=2.3.0.250703
  - pip=25.0.1
  - pyomo=6.9.2
  - pytest=8.4.0
  - python=3.12.2
  - rich=13.9.4
  - rich-argparse=1.7.0
  - pip:
      - pulp==2.9.0
