[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "InOutModule"
version = "0.0.0-dev"
readme = "README.md"

[tool.setuptools]
py-modules = ['CaseStudy', 'ExcelReader', 'ExcelWriter', 'printer', 'SQLiteWriter', 'TableDefinition']
packages = ['PyPSA']

[tool.setuptools.package-data]
PyPSA = ['pypsa_lego_mapping_config.yaml', 'README.md']

[tool.pytest.ini_options]
pythonpath = [".."]
