name: CI

on:
  push:
  pull_request:

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3.2.0
        with:
          environment-file: InOutModule/environment.yml
          activate-environment: InOutModule_env

      - name: Run tests
        run: pytest